services:
  icbc-catcher:
    build: .
    container_name: icbc-road-test-catcher
    environment:
      - TZ=America/Vancouver
      - USER_LAST_NAME=
      - USER_LICENSE_NUMBER=
      - USER_KEYWORD=
      - USER_GMAIL=
      - USER_GMAIL_APP_PASSWORD=
      - DESIRED_DATE_START=
      - DESIRED_DATE_END=
      - LOCATION_IDS=
