name: Check ICBC Appointments

on:
  schedule:
    - cron: '45 22,4,10,16 * * *'  # every 6 hours
  workflow_dispatch:        # allow manual trigger

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run appointment checker
        env:
          USER_LICENSE_NUMBER: ${{ secrets.USER_LICENSE_NUMBER }}
          USER_KEYWORD: ${{ secrets.USER_KEYWORD }}
          USER_GMAIL_APP_PASSWORD: ${{ secrets.USER_GMAIL_APP_PASSWORD }}
          USER_LAST_NAME: ${{ vars.USER_LAST_NAME }}
          USER_GMAIL: ${{ vars.USER_GMAIL }}
          DESIRED_DATE_START: ${{ vars.DESIRED_DATE_START }}
          DESIRED_DATE_END: ${{ vars.DESIRED_DATE_END }}
          LOCATION_IDS: ${{ vars.LOCATION_IDS }}
        run: python main.py
